# Site settings
title: International Programs - Afghan Agriculture
email: seacersion@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
   e-Afghan Ag "provides credible relevant information to those helping farmers in Afghanistan."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://epakag.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 10

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
